package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComOllvenSubmodulesRefsHeadsMain1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComOllvenSubmodulesRefsHeadsMain1")
    name = "https://github.com/ollven/Submodules#refs/heads/main (1)"
    url = "https://github.com/ollven/Submodules"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    checkoutSubmodules = GitVcsRoot.CheckoutSubmodules.IGNORE
    userForTags = "ollven<ollven@yandex.ru>"
    authMethod = password {
        userName = "ollven"
        password = "credentialsJSON:9fd10c2d-c48f-40aa-9156-19acfe23cab2"
    }
}))

