package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the vcsRoot with id = 'HttpsGithubComOllvenSubmodulesRefsHeadsMain1'
from your code, and delete the patch script.
*/
deleteVcsRoot(RelativeId("HttpsGithubComOllvenSubmodulesRefsHeadsMain1"))

